apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-app-deployment
  labels:
    app: food-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
      - name: food-app
        image: ndinevski/food-app:32
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
